name: cartoon-face-detection
channels:
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2019.11.28
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.63.1
  - graphite2=1.3.13
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2019.4
  - jasper=2.0.14
  - jpeg=9b
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libtiff=4.1.0
  - libvpx=1.7.0
  - libxml2=2.9.9
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - opencv=3.4.2
  - openssl=1.1.1d
  - pcre=8.43
  - pip=20.0.2
  - pixman=0.38.0
  - py-opencv=3.4.2
  - python=3.7.6
  - readline=7.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - opencv-contrib-python==4.2.0.32

